standalone: "true"
sonar_name: "blueview_p900"
sonar_x: "6"
sonar_y: "0"
sonar_z: "-93"
sonar_roll: "0"
sonar_pitch: "0.25"
sonar_yaw: "0"
maxDistance: "12"
raySkips: "10"
sonar_scale: "'1 1 1'"
sonar_image_topic: "sonar_image"
sonar_image_raw_topic: "sonar_image_raw"
ray_visual: "true"
plotScaler: "0"
sensorGain: "0.4"
writeLog: "false"
debug: "false"
writeFrameInterval: "5"
artificialVehicleVibration: "false"
constantReflectivity: "true"
reflectivityDatabaseFile: "variationalReflectivityDatabase.csv"