standalone: "true"
gpu_ray: "true"
sonar_name: "blueview_p900"
sonar_x: "6"
sonar_y: "0"
sonar_z: "-93"
sonar_roll: "0"
sonar_pitch: "0.25"
sonar_yaw: "0"
maxDistance: "10"
fidelity: "500"
raySkips: "1"
sonar_scale: "'1 1 1'"
sonar_image_topic: "sonar_image"
sonar_image_raw_topic: "sonar_image_raw"
ray_visual: "true"
plotScaler: "0"
sensorGain: "0.04"
writeLog: "false"
debug: "false"
writeFrameInterval: "5"
gaussian_noise_mean: "0.0"
gaussian_noise_stddev: "0.0"