standalone: "true"
sonar_name: "blueview_p900"
sonar_x: "0"
sonar_y: "2"
sonar_z: "3"
sonar_roll: "0"
sonar_pitch: "0"
sonar_yaw: "-1.5708"
maxDistance: "4"
raySkips: "1"
sonar_scale: "'1 1 1'"
sonar_image_topic: "sonar_image"
sonar_image_raw_topic: "sonar_image_raw"
ray_visual: "true"
plotScaler: "0"
sensorGain: "0.04"
writeLog: "false"
debug: "false"
writeFrameInterval: "5"
artificialVehicleVibration: "false"
constantReflectivity: "true"
reflectivityDatabaseFile: "variationalReflectivityDatabase.csv"